// This file is generated by scripts/sync-skill-catalog.ts.
// Source of truth: skills/*/SKILL.md frontmatter.

type SkillMetadata = {
  agentsLabel: string
}

const CORE_SKILL_METADATA_BY_ID = {
  'granite-routing': {
    agentsLabel: 'route / page / navigation 패턴',
  },
  'tds-ui': {
    agentsLabel: 'TDS UI 선택과 form 패턴',
  },
} as const satisfies Record<string, SkillMetadata>

const OPTIONAL_SKILL_METADATA_BY_ID = {
  'backoffice-react': {
    agentsLabel: 'backoffice React 작업',
  },
  'cloudflare-worker': {
    agentsLabel: 'Cloudflare Worker 작업',
  },
  'supabase-project': {
    agentsLabel: 'Supabase project 작업',
  },
  'firebase-functions': {
    agentsLabel: 'Firebase Functions 작업',
  },
  'trpc-boundary': {
    agentsLabel: 'tRPC boundary 변경',
  },
} as const satisfies Record<string, SkillMetadata>

export type CoreSkillId = keyof typeof CORE_SKILL_METADATA_BY_ID
export type OptionalSkillId = keyof typeof OPTIONAL_SKILL_METADATA_BY_ID
export type SkillId = CoreSkillId | OptionalSkillId

export type SkillDefinition = {
  id: SkillId
  agentsLabel: string
}

function createSkillReferenceDefinition<TId extends SkillId>(id: TId, metadata: SkillMetadata) {
  return {
    id,
    agentsLabel: metadata.agentsLabel,
  }
}

function resolveCoreSkillDefinition(id: CoreSkillId): SkillDefinition {
  return createSkillReferenceDefinition(id, CORE_SKILL_METADATA_BY_ID[id])
}

function createOptionalSkillDefinition(id: OptionalSkillId): SkillDefinition {
  return createSkillReferenceDefinition(id, OPTIONAL_SKILL_METADATA_BY_ID[id])
}

export const CORE_SKILL_DEFINITIONS = (Object.keys(CORE_SKILL_METADATA_BY_ID) as CoreSkillId[]).map(
  resolveCoreSkillDefinition,
)

export const OPTIONAL_SKILL_IDS = Object.keys(OPTIONAL_SKILL_METADATA_BY_ID) as OptionalSkillId[]

export const OPTIONAL_SKILL_DEFINITIONS = OPTIONAL_SKILL_IDS.map(createOptionalSkillDefinition)

export const SKILL_CATALOG: SkillDefinition[] = [
  ...CORE_SKILL_DEFINITIONS,
  ...OPTIONAL_SKILL_DEFINITIONS,
]

export function getSkillDefinition(id: SkillId) {
  if (id in CORE_SKILL_METADATA_BY_ID) {
    return resolveCoreSkillDefinition(id as CoreSkillId)
  }

  if (id in OPTIONAL_SKILL_METADATA_BY_ID) {
    return createOptionalSkillDefinition(id as OptionalSkillId)
  }

  throw new Error(`알 수 없는 skill id입니다: ${id}`)
}

export function resolveOptionalSkillDefinition(id: OptionalSkillId) {
  return createOptionalSkillDefinition(id)
}
