import { readdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  parseSkillFrontmatter,
  type SkillFrontmatter,
} from '../packages/create-rn-miniapp/src/skills-frontmatter.js'

const repoRoot = fileURLToPath(new URL('..', import.meta.url))
const skillsRoot = path.join(repoRoot, 'skills')
const outputPath = path.join(repoRoot, 'packages/create-rn-miniapp/src/templates/skill-catalog.ts')

async function main() {
  const skillEntries = (await readdir(skillsRoot, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .sort((left, right) => left.name.localeCompare(right.name))

  const skills: SkillFrontmatter[] = []

  for (const entry of skillEntries) {
    const skillPath = path.join(skillsRoot, entry.name, 'SKILL.md')
    const source = await readFile(skillPath, 'utf8').catch(() => null)

    if (!source) {
      continue
    }

    skills.push(parseSkillFrontmatter(source, entry.name))
  }

  skills.sort((left, right) => left.order - right.order || left.id.localeCompare(right.id))

  const coreSkills = skills.filter((skill) => skill.category === 'core')
  const optionalSkills = skills.filter((skill) => skill.category === 'optional')

  const nextSource = [
    '// This file is generated by scripts/sync-skill-catalog.ts.',
    '// Source of truth: skills/*/SKILL.md frontmatter.',
    '',
    'type SkillMetadata = {',
    '  agentsLabel: string',
    '}',
    '',
    'const CORE_SKILL_METADATA_BY_ID = {',
    renderSkillMetadataEntries(coreSkills),
    '} as const satisfies Record<string, SkillMetadata>',
    '',
    'const OPTIONAL_SKILL_METADATA_BY_ID = {',
    renderSkillMetadataEntries(optionalSkills),
    '} as const satisfies Record<string, SkillMetadata>',
    '',
    'export type CoreSkillId = keyof typeof CORE_SKILL_METADATA_BY_ID',
    'export type OptionalSkillId = keyof typeof OPTIONAL_SKILL_METADATA_BY_ID',
    'export type SkillId = CoreSkillId | OptionalSkillId',
    '',
    'export type SkillDefinition = {',
    '  id: SkillId',
    '  agentsLabel: string',
    '}',
    '',
    'function createSkillReferenceDefinition<TId extends SkillId>(id: TId, metadata: SkillMetadata) {',
    '  return {',
    '    id,',
    '    agentsLabel: metadata.agentsLabel,',
    '  }',
    '}',
    '',
    'function resolveCoreSkillDefinition(id: CoreSkillId): SkillDefinition {',
    '  return createSkillReferenceDefinition(id, CORE_SKILL_METADATA_BY_ID[id])',
    '}',
    '',
    'function createOptionalSkillDefinition(id: OptionalSkillId): SkillDefinition {',
    '  return createSkillReferenceDefinition(id, OPTIONAL_SKILL_METADATA_BY_ID[id])',
    '}',
    '',
    'export const CORE_SKILL_DEFINITIONS = (Object.keys(CORE_SKILL_METADATA_BY_ID) as CoreSkillId[]).map(',
    '  resolveCoreSkillDefinition,',
    ')',
    '',
    'export const OPTIONAL_SKILL_IDS = Object.keys(OPTIONAL_SKILL_METADATA_BY_ID) as OptionalSkillId[]',
    '',
    'export const OPTIONAL_SKILL_DEFINITIONS = OPTIONAL_SKILL_IDS.map(createOptionalSkillDefinition)',
    '',
    'export const SKILL_CATALOG: SkillDefinition[] = [',
    '  ...CORE_SKILL_DEFINITIONS,',
    '  ...OPTIONAL_SKILL_DEFINITIONS,',
    ']',
    '',
    'export function getSkillDefinition(id: SkillId) {',
    '  if (id in CORE_SKILL_METADATA_BY_ID) {',
    '    return resolveCoreSkillDefinition(id as CoreSkillId)',
    '  }',
    '',
    '  if (id in OPTIONAL_SKILL_METADATA_BY_ID) {',
    '    return createOptionalSkillDefinition(id as OptionalSkillId)',
    '  }',
    '',
    '  throw new Error(`알 수 없는 skill id입니다: ' + '$' + '{id}`)',
    '}',
    '',
    'export function resolveOptionalSkillDefinition(id: OptionalSkillId) {',
    '  return createOptionalSkillDefinition(id)',
    '}',
    '',
  ].join('\n')

  await writeFile(outputPath, nextSource, 'utf8')
}

function renderSkillMetadataEntries(skills: SkillFrontmatter[]) {
  return skills
    .map(
      (skill) =>
        `  '${skill.id}': {\n    agentsLabel: '${escapeSingleQuotes(skill.agentsLabel)}',\n  },`,
    )
    .join('\n')
}

function escapeSingleQuotes(source: string) {
  return source.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}

main().catch((error: unknown) => {
  console.error(error)
  process.exitCode = 1
})
